### ISSUE TITLE
Bank Account Module

### ISSUE THREAD

**Issue by HazeCom** [ShubhamRandive1/Wallet_Payment_Application#11]
- [x] BankAccount
- [x] BankAccountDTO
- [x] BankAccountDao
- [x] BankAccountService
- [x] BankAccountServiceImpl
- [x] BankAccountException
- [x] BankAccountController

**Comment by yogeshsaini21** [comment]
exception and 2 method remaining in implementation

**Comment by ShubhamRandive1** [comment]
done
