### ISSUE TITLE
Bill Payment module

### ISSUE THREAD

**Issue by HazeCom** [ShubhamRandive1/Wallet_Payment_Application#7]
- [x] BillPayment 
- [x] BillPaymentDTO
- [x] BillPaymentDao
- [x] BillPaymentService
- [x] BillPaymentServiceImpl
- [x] BillPaymentException
- [x] BillPaymentController

**Comment by BhanuPrathapGoud** [comment]
BillPayment Model and Repo Completed

**Comment by ShubhamRandive1** [comment]
done
